name: deploy
on:
  push: 
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
     - name: instal redis cli
       run: sudo apt-get update -y && sudo apt-get install redis-tools -y
       
     - name: print secrets
       run: echo "${{ secrets.NAME }}"

     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
          node-version: '18'


