name: deploy
on:
  push: 
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
     - name: instal redis cli
       run: sudo apt-get update -y && sudo apt-get install redis-tools -y

     - name: print secrets
       run: echo "${{ secrets.NAME }}"

     - name: test redis
       run : redis-cli -h localhost -p 6379 ping
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
          node-version: '18'

     - name: Install dependencies
       run: npm install

     - name: Run tests
       run: npm test

     - name: Build project
       run: npm run build

     - name: Upload build artifacts
       uses: actions/upload-artifact@v4
       with:
         path: public/

         
  deploy:
   if: ${{always()}} # This ensures the deploy job runs even if the build fails
   runs-on: ubuntu-latest
   needs: build
   environment:
     name: giithub-pages
     url: ${{ steps.deploy.outputs.page_url }}
   steps:
        - name: deploy
          id: deploy
          uses: actions/deploy-pages@v4
          
        

 

  



